apiVersion: v1
kind: Secret
metadata:
    name: mealie-secret
    namespace: mealie
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:a0oRP83sX35MZmVDdagN/UypmG8ysLwOWBzmwH6jpEGOSoIgCHNQprmol1s=,iv:ZwxLq533KRWBqz67qvNykDNam/OpgtMVqrq9j/Qy3Yw=,tag:85YTasEJAiPrHtgnTF/ioQ==,type:str]
sops:
    age:
        - recipient: age15jjwhal370uylrdqnz6jfdefjm0l6k69ausa0rruyshr2utf6suq83g5x8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcm0vMVBYU1F3czQrbkMr
            N1pWNGQ4c3FjTTBTSFpIbTRyZVBGNC9PRlgwCk9wYWFUZCtTZ1lUcDF4WWttOWgx
            MjdpMXJQWmtwTXpzMkFWZDNhaEFKWHMKLS0tIGUzWVQ3a1czU3VLSzhRZDd4ZUlq
            dHFyVWpUdGRXY0Vnek1EbVNFMldBOVUKYpAYUx2pq1rTNrksBcGKKNV0BLZf+f4o
            P123KbcXwYJ8POsBb6ISq9oTD3EYyd+gf+cyOjmeozGEH8VaIxsOTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T16:29:10Z"
    mac: ENC[AES256_GCM,data:UGZKZlWrzZ2fVwuXrg6X+5Tac4uduuVcS9e2H95Kjtr6Ipawpxik5l61zpIwhNXPzFGuchA3kzUZbjJWOcLgditjrR9MsxiZLTa4DUuK0E6+b2n52qO/tskjcVpA9gS93ZxT5JGGv5i8UzmxxjHk2Q7Rd6X7LX+du2uNzNtxCW4=,iv:ROYwBnyAfDNuMNqDG7CAnthI6LBg4SbiuybbCU7xzDw=,tag:dsDvtfQ4Tqhvcw/5QnYYfg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
